name: Build and Push Docker Image

# Quando executar: a cada push na branch main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Faz checkout do código
    - name: Checkout code
      uses: actions/checkout@v4
      
    # 2. Configura Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    # 3. Login no Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # 4. Build e Push da imagem
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./primeira-app
        file: ./primeira-app/Dockerfile
        push: true
        tags: |
          rogersonoliveira/devops-primeira-app:latest
          rogersonoliveira/devops-primeira-app:${{ github.sha }}
    
    # 5. Teste simples - verifica se a imagem foi criada
    - name: Test Docker image
      run: |
        docker run --rm -d -p 8080:80 --name test-app rogersonoliveira/devops-primeira-app:latest
        sleep 5
        curl -f http://localhost:8080 || exit 1
        docker stop test-app
        echo "✅ Teste passou! Aplicação está funcionando!"